# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/configuredialog.ui'
#
# Created: Fri Oct  9 13:31:20 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(545, 384)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.configGroupBox = QtGui.QGroupBox(Dialog)
        self.configGroupBox.setTitle("")
        self.configGroupBox.setObjectName("configGroupBox")
        self.formLayout = QtGui.QFormLayout(self.configGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit0 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit0.setObjectName("lineEdit0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit0)
        self.label_5 = QtGui.QLabel(self.configGroupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditMC = QtGui.QLineEdit(self.configGroupBox)
        self.lineEditMC.setObjectName("lineEditMC")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditMC)
        self.label = QtGui.QLabel(self.configGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditLC = QtGui.QLineEdit(self.configGroupBox)
        self.lineEditLC.setObjectName("lineEditLC")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditLC)
        self.label_3 = QtGui.QLabel(self.configGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditMM = QtGui.QLineEdit(self.configGroupBox)
        self.lineEditMM.setObjectName("lineEditMM")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditMM)
        self.label_2 = QtGui.QLabel(self.configGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditLM = QtGui.QLineEdit(self.configGroupBox)
        self.lineEditLM.setObjectName("lineEditLM")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditLM)
        self.label_4 = QtGui.QLabel(self.configGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditTT = QtGui.QLineEdit(self.configGroupBox)
        self.lineEditTT.setObjectName("lineEditTT")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditTT)
        self.label_6 = QtGui.QLabel(self.configGroupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditKC = QtGui.QLineEdit(self.configGroupBox)
        self.lineEditKC.setObjectName("lineEditKC")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditKC)
        self.label0 = QtGui.QLabel(self.configGroupBox)
        self.label0.setObjectName("label0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label0)
        self.label_8 = QtGui.QLabel(self.configGroupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.configGroupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label_7 = QtGui.QLabel(self.configGroupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_7)
        self.checkBoxGUI = QtGui.QCheckBox(self.configGroupBox)
        self.checkBoxGUI.setText("")
        self.checkBoxGUI.setObjectName("checkBoxGUI")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.checkBoxGUI)
        self.gridLayout.addWidget(self.configGroupBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit0, self.lineEditMC)
        Dialog.setTabOrder(self.lineEditMC, self.lineEditLC)
        Dialog.setTabOrder(self.lineEditLC, self.lineEditMM)
        Dialog.setTabOrder(self.lineEditMM, self.lineEditLM)
        Dialog.setTabOrder(self.lineEditLM, self.lineEditTT)
        Dialog.setTabOrder(self.lineEditTT, self.lineEditKC)
        Dialog.setTabOrder(self.lineEditKC, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configure Tibia Fibula Registration Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Medial Epicondyle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Lateral Epicondyle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Medial Maleolus:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Lateral Maleolus:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Tibial Tuberosity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Knee Centre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label0.setText(QtGui.QApplication.translate("Dialog", "identifier:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Marker Correction:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "GUI:", None, QtGui.QApplication.UnicodeUTF8))

